module.exports = {
  collectionName: 'gyms',
  info: {
    singularName: 'gym',
    pluralName: 'gyms',
    displayName: 'Gym',
  },
  options: { draftAndPublish: false },
  attributes: {
    name: { type: 'string', required: true },
    slug: { type: 'uid', targetField: 'name', required: true, unique: true },
    address: { type: 'string' },
    phone: { type: 'string' },
    email: { type: 'email' },
    logo: { type: 'media', multiple: false, allowedTypes: ['images'] },
    currency: { type: 'string', default: 'MXN' },
    receiptFooter: { type: 'richtext' },
    defaultMembershipDuration: { type: 'integer', default: 30 },
    lowStockThreshold: { type: 'integer', default: 5 },
    users: {
      type: 'relation', relation: 'oneToMany',
      target: 'plugin::users-permissions.user', mappedBy: 'gym',
    },
    clients: { type: 'relation', relation: 'oneToMany', target: 'api::client.client', mappedBy: 'gym' },
    memberships: { type: 'relation', relation: 'oneToMany', target: 'api::membership.membership', mappedBy: 'gym' },
    clientMemberships: { type: 'relation', relation: 'oneToMany', target: 'api::client-membership.client-membership', mappedBy: 'gym' },
    payments: { type: 'relation', relation: 'oneToMany', target: 'api::payment.payment', mappedBy: 'gym' },
    products: { type: 'relation', relation: 'oneToMany', target: 'api::product.product', mappedBy: 'gym' },
    productCategories: { type: 'relation', relation: 'oneToMany', target: 'api::product-category.product-category', mappedBy: 'gym' },
    inventoryMovements: { type: 'relation', relation: 'oneToMany', target: 'api::inventory-movement.inventory-movement', mappedBy: 'gym' },
    sales: { type: 'relation', relation: 'oneToMany', target: 'api::sale.sale', mappedBy: 'gym' },
    saleItems: { type: 'relation', relation: 'oneToMany', target: 'api::sale-item.sale-item', mappedBy: 'gym' },
    auditLogs: { type: 'relation', relation: 'oneToMany', target: 'api::audit-log.audit-log', mappedBy: 'gym' },
    settings: {
      type: 'relation', relation: 'oneToOne',
      target: 'api::setting.setting', mappedBy: 'gym',
    },
  },
}
